### PR TITLE
fix infinity conversion

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by dpetrisko** [comment]
I'm not sure on this one.  The documentation on the website explicitly defines (2^k + 2 − n) as the maximum subnormal, so this would be a bug with the recoded format itself, which I would find surprising.  What's the testcase this is failing?

**Comment by tommydcjung** [comment]
image

Try plugging in 0_110x_xxxx_xxxx_...., which is supposed to be infinity in recoded format. isSubnormal goes to x, and the sig output goes to x.

**Comment by tommydcjung** [comment]
This is the fix provided by John Hauser.

**Comment by dpetrisko** [comment]
Oh, so this is an X fix, I see.  When you say provided by John Hauser, you mean you emailed him this bug?

**Comment by dpetrisko** [comment]
Wouldn't || (sExp>>(expWidth - 1) == 'b00); cause zeros to be detected as subnormal?

**Comment by tommydcjung** [comment]
It is weird to include zero as subnormal, but look where isSubnormal is used in this particular module. It's used to zero out exp, and picked fractOut. So I think it's okay?

**Comment by dpetrisko** [comment]
Got it, I think it's fine.  The fractOut is (sig>>1)>>denormShiftDist, which for zero is 00000 in both recoded and raw.  And then zero and subnormal exponents are both zero, so it doesn't matter for that selection either.

Maybe just add a comment about this weird behavior and where you got this snippet?  Otherwise LGTM

**Comment by taylor-bsg** [comment]
Did you find the bug and report to Hauser, or did you find it on his
website, or ...

**Pull request merged**
